#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "gc.h"

// This testing module is generated by AI

// --- Helper to clear the VM after a test ---
void freeVM(VM* vm) {
  vm->stackSize = 0;
  gc(vm);  // Clears all objects
  free(vm);
}

// --- Test Cases ---

void testPreserveRoots() {
  printf("Running testPreserveRoots...\n");
  VM* vm = newVM();

  pushInt(vm, 1);
  pushInt(vm, 2);

  gc(vm);

  assert(vm->currentAllocations == 2 && "Should have preserved 2 objects.");
  freeVM(vm);
}

void testCollectUnreached() {
  printf("Running testCollectUnreached...\n");
  VM* vm = newVM();

  pushInt(vm, 1);
  pushInt(vm, 2);

  // Pop both off the stack, making them unreachable
  pop(vm);
  pop(vm);

  gc(vm);

  assert(vm->currentAllocations == 0 && "Should have collected both objects.");
  freeVM(vm);
}

void testReachabilityNested() {
  printf("Running testReachabilityNested...\n");
  VM* vm = newVM();

  pushInt(vm, 1);
  pushInt(vm, 2);
  pushPair(vm);  // Pops 1 and 2, pushes a Pair containing them
  pushInt(vm, 3);
  pushInt(vm, 4);
  pushPair(vm);  // Pops 3 and 4, pushes a Pair containing them
  pushPair(vm);  // Pops the two Pairs, pushes a Pair containing them

  printf("total number of allocations %d\n", vm->currentAllocations);

  gc(vm);

  printf("total number of allocations %d\n", vm->currentAllocations);

  // 1 pair holding 2 pairs holding 4 ints = 7 objects total
  assert(vm->currentAllocations == 7 &&
         "Should have preserved all 7 nested objects.");
  freeVM(vm);
}

void testCycles() {
  printf("Running testCycles...\n");
  VM* vm = newVM();

  pushInt(vm, 1);
  pushInt(vm, 2);
  Object* a = pushPair(vm);

  pushInt(vm, 3);
  pushInt(vm, 4);
  Object* b = pushPair(vm);

  // Create a cycle: a's tail points to b, b's tail points to a.
  a->tail = b;
  b->tail = a;

  gc(vm);

  assert(vm->currentAllocations == 4 &&
         "Should have handled the cycle safely.");
  freeVM(vm);
}

void testAutoGcTrigger() {
  printf("Running testAutoGcTrigger...\n");
  VM* vm = newVM();

  // Assuming MAX_ALLOCATION is defined (usually 8 or 256 in these tutorials)
  for (int i = 0; i < vm->maxAllocations + 1; i++) {
    pushInt(vm, i);
    pop(vm);  // Immediately pop so it becomes garbage
  }

  // Because we pop immediately, the stack is empty.
  // When the final allocation hits maxAllocations, it will trigger gc().
  // That GC will sweep everything prior, leaving only the 1 object we just
  // allocated.
  assert(vm->currentAllocations == 1 &&
         "GC should have triggered automatically.");
  freeVM(vm);
}

int main() {
  testPreserveRoots();
  testCollectUnreached();
  testReachabilityNested();
  testCycles();
  testAutoGcTrigger();

  printf("All GC tests passed successfully!\n");
  return 0;
}